# If you modify this file, you need to recompile.

[bl_default]
ic3 = "ic3"
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false"
ic3_no_parent = "ic3 --drop-po=false --parent-lemma=false"
ic3_abs_cst = "ic3 --abs-cst"
ic3_abs_all = "ic3 --abs-cst --abs-trans"
ic3_predprop = "ic3 --pred-prop"
ic3_ctg_limit = "ic3 --ctg-max 5 --ctg-limit 15 --drop-po=false"
ic3_inn = "ic3 --inn"
ic3_inn_ctp = "ic3 --inn --ctp"
ic3_inn_noctg = "ic3 --inn --ctg=false"
ic3_inn_dynamic = "ic3 --inn --dynamic --drop-po=false"
bmc = "bmc --step 1"
bmc_kissat_10 = "bmc --kissat --step 10"
bmc_kissat_65 = "bmc --kissat --step 65"
bmc_kissat_dyn = "bmc --kissat --dyn-step"
kind = "kind --step 1 --simple-path"

[wl_default]
ic3 = "ic3"
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false"
ic3_no_parent = "ic3 --drop-po=false --parent-lemma=false"
ic3_abs_cst = "ic3 --abs-cst"
ic3_abs_all = "ic3 --abs-cst --abs-trans"
ic3_predprop = "ic3 --pred-prop"
ic3_ctg_limit = "ic3 --ctg-max 5 --ctg-limit 15 --drop-po=false"
ic3_inn = "ic3 --inn"
ic3_inn_ctp = "ic3 --inn --ctp"
ic3_inn_noctg = "ic3 --inn --ctg=false"
ic3_inn_dynamic = "ic3 --inn --dynamic --drop-po=false"
bmc = "bmc --step 1"
bmc_kissat_10 = "bmc --kissat --step 10"
bmc_kissat_dyn = "bmc --kissat --dyn-step"
wlbmc = "wl-bmc"
wlkind = "wl-kind --step 1"

[light]
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false"
ic3_abs_all = "ic3 --abs-cst --abs-trans"
ic3_predprop = "ic3 --pred-prop"
ic3_inn = "ic3 --inn"
ic3_inn_ctp = "ic3 --inn --ctp"
ic3_inn_noctg = "ic3 --inn --ctg=false"
bmc = "bmc --step 1"
bmc_kissat_10 = "bmc --kissat --step 10"

[bl_hwmcc]
ic3 = "ic3"
ic3_no_preproc = "ic3 --ctg=false --frts=false --scorr=false --drop-po=false"
ic3_no_parent = "ic3 --drop-po=false --parent-lemma=false"
ic3_abs_cst = "ic3 --abs-cst"
ic3_abs_all = "ic3 --abs-cst --abs-trans"
ic3_dynamic = "ic3 --abs-cst --abs-trans --dynamic --drop-po=false"
ic3_ctg_limit = "ic3 --ctg-max 5 --ctg-limit 15 --drop-po=false"
ic3_inn = "ic3 --inn"
ic3_inn_ctp = "ic3 --inn --ctp"
ic3_inn_noctg = "ic3 --inn --ctg=false"
ic3_inn_dynamic = "ic3 --inn --dynamic --drop-po=false"
bmc = "bmc --step 1"
bmc_kissat_10 = "bmc --kissat --step 10"
bmc_kissat_65 = "bmc --kissat --step 65"
bmc_kissat_dyn = "bmc --kissat --dyn-step"
kind = "kind --step 1"
